version: '3.1'
services:
  python-template:
    container_name: python_template
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.flake8:/var/app/.flake8
      - ./tests:/var/app/tests
      - ./main.py:/var/app/main.py
      - ./reaname_me:/var/app/rename_me
    ports:
      - 5000:5000
    environment:
      TZ: Asia/Tokyo
    tty: true